apiVersion: apps/v1
kind :  Deployment
metadata:
  name: app-deployment
  namespace: dev
  labels:
    name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: wil42/playground:v1
          ports:
            - containerPort : 8888