apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-service
  name: app-service
spec:
  ports:
  - name: http
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: app
  type: NodePort